version: '3.3'

services:
  gateway:
    build: gateway/
    ports: ["5012:80"]

  api:
    build: exercisor/
    environment:
      - EXERCISOR_MONGO_HOST=mongodb
    depends_on:
      - mongodb
    restart: "unless-stopped"

  ui:
    build: exercisor-ui/
    restart: "unless-stopped"

  mongodb:
    image: mongo:3.4
    volumes:
      - exercisor-mongo-data:/data/db
    restart: "unless-stopped"

volumes:
  exercisor-mongo-data:
