export const EXERCISE_VIEW_ERROR = 'EXERCISE_VIEW_ERROR';
export const EXERCISE_TABLE_ERROR = 'EXERCISE_TABLE_ERROR';
export const EXERCISE_MAP_ERROR = 'EXERCISE_MAP_ERROR';
export const EXERCISE_GOALS_ERROR = 'EXERCISE_GOALS_ERROR';

export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_ERROR = 'LOGIN_ERROR';
